version: 2

references:

  install_backend_dependencies: &install_backend_dependencies
    run:
      name: Install backend dependencies
      command: |
        cd server
        pipenv install
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
        environment:
          FLASK_CONFIG: testing
          TEST_DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ''
    steps:
      - checkout
      - *install_backend_dependencies
      - run: cd server && pipenv run python -m unittest discover -s test -p '*_test.py'

