import os

TEAM_NAME = os.environ['TEAM_NAME']

POSTGRES_URL = os.environ["POSTGRES_URL"]
POSTGRES_USERNAME = os.environ["POSTGRES_USERNAME"]
POSTGRES_PASSWORD = os.environ["POSTGRES_PASSWORD"]
POSTGRES_DATABASE = os.environ["POSTGRES_DATABASE"]

STRIPE_PUBLISHABLE_KEY_TEST = os.environ["STRIPE_PUBLISHABLE_KEY_TEST"]
STRIPE_SECRET_KEY_TEST = os.environ["STRIPE_SECRET_KEY_TEST"]
STRIPE_CLIENT_ID_TEST = os.environ["STRIPE_CLIENT_ID_TEST"]
