"""empty message
Revision ID: 3fa3cef41646
Revises: 3c4b24ad2a08
Create Date: 2019-11-29 16:47:55.288558
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa3cef41646'
down_revision = '3c4b24ad2a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(
        'stripe_customer_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column(
        'stripe_transfer_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stripe_transfer_id')
    op.drop_column('user', 'stripe_customer_id')
    # ### end Alembic commands ###
