"""empty message

Revision ID: c871995f9133
Revises: 592d13a3cb75
Create Date: 2019-11-22 05:33:54.925663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

#2
# revision identifiers, used by Alembic.
revision = 'c871995f9133'
down_revision = '592d13a3cb75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tattoo_image',
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('mimetype', sa.String(length=255), nullable=False),
    sa.Column('original', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('width', 'height', 'submission_id', 'order_index')
    )
    op.drop_column('submission', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_table('tattoo_image')
    # ### end Alembic commands ###
